### ISSUE TITLE
Tienes un fallo en el modal

### ISSUE THREAD

**Issue by gaal1le0** [Criis21/The-Instagram-Photo-Feed-with-Bootstrap#5]
https://github.com/Criis21/The-Instagram-Photo-Feed-with-Bootstrap/blob/28aba2cd08fcf0db4992470014b7bff430b10b91/index.html#L34

Buenas Criss!! Tenemos un fallo en el modal, si le das click en el botón no se te abre el modal de create new post. Por lo que tenemos que modificarlo, te adjunto captura para que lo veas.

<img width="1433" alt="Captura de pantalla 2021-11-04 a las 13 23 16" src="https://user-images.githubusercontent.com/84098854/140313081-bdca2ae3-a22e-4a41-96d9-64f1382f9001.png">

Además tenemos otro problema en la visualización del elemento de settings, cuando abro el dropdown se me agranda la pantalla y nos respeta el width 100%. Te adjunto captura para que puedas ver el estado de lo que te comento.

<img width="1434" alt="Captura de pantalla 2021-11-04 a las 13 23 30" src="https://user-images.githubusercontent.com/84098854/140313212-4ffd5bb1-a508-4fef-b381-948f1bd0eede.png">

Además he visto que has puesto el css inline, eso está prohibido no puedes usar la etiqueta `style` en el HTML, debes colocar si o sí el estilo en el css.

Te pido porfi que revises estas dos cosas para que puedas corregirlas y pueda revisar de nuevo la tarea. Todo lo demás está perfecto pero eso está fallando y es bastante importante.

No te olvides de cerrar el ISSUE cuando hayas acabado

PD: Estas mejorando bastante, espero tu respuesta.

**Comment by Criis21** [comment]
Buenas Manu,
He cambiado el setting y ya funciona bien y he quitado todo el css inlines (menos en las imágenes del primer pills porque no soy capaz...) pero no soy capaz de que funcione el modal. Lo he cambiado por otro y sigo sin poder, no se que toque al modificar la anterior vez...
Lo vemos esta tarde antes de la clase?

**Comment by gaal1le0** [comment]
Buenas tardes Criss,

Te comento, tengo Justo una mentoria antes pero cuando os separe en grupos para hacer ejercicios me llamas y lo resolvemos 😀

**Comment by Criis21** [comment]
Perfecto, mil gracias

**Comment by gaal1le0** [comment]
Tu recuérdamelo que a mi se me olvida 😊
